micronaut:
  application:
    name: keyManagerGrpc
datasources:
  default:
    url: jdbc:postgresql://localhost:5432/db_pix
    driverClassName: org.postgresql.Driver
    username: postgres
    password: root
    schema-generate: CREATE_DROP
    dialect: POSTGRES
jpa.default.properties.hibernate.hbm2ddl.auto: update
jpa.default.properties.hibernate.show_sql: true

grpc:
  server:
    port: ${SERVER_PORT:50051}
    keep-alive-time: 1h
    max-inbound-message-size: 1024


